/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2018-02-07 09:16:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>TweetBook</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/accueil.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"cotn_principal\">\n");
      out.write("\t\t<div class=\"cont_centrar\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"cont_login\">\n");
      out.write("\t\t\t\t<div class=\"cont_info_log_sign_up\">\n");
      out.write("\t\t\t\t\t<div class=\"col_md_login\">\n");
      out.write("\t\t\t\t\t\t<div class=\"cont_ba_opcitiy\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<h2>LOGIN</h2>\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn_login\" onclick=\"cambiar_login()\">LOGIN\n");
      out.write("\t\t\t\t\t\t\t\t!!!</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col_md_sign_up\">\n");
      out.write("\t\t\t\t\t\t<div class=\"cont_ba_opcitiy\">\n");
      out.write("\t\t\t\t\t\t\t<h2>SIGN UP</h2>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t\t\tIt's FREE<br>\n");
      out.write("\t\t\t\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn_sign_up\" onclick=\"cambiar_sign_up()\">SIGN\n");
      out.write("\t\t\t\t\t\t\t\tUP !!!</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"cont_back_info\">\n");
      out.write("\t\t\t\t\t<div class=\"cont_img_back_grey\">\n");
      out.write("\t\t\t\t\t\t<img\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d\"\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"cont_forms\">\n");
      out.write("\t\t\t\t\t<div class=\"cont_img_back_\">\n");
      out.write("\t\t\t\t\t\t<img\n");
      out.write("\t\t\t\t\t\t\tsrc=\"https://images.unsplash.com/42/U7Fc1sy5SCUDIu4tlJY3_NY_by_PhilippHenzler_philmotion.de.jpg?ixlib=rb-0.3.5&q=50&fm=jpg&crop=entropy&s=7686972873678f32efaf2cd79671673d\"\n");
      out.write("\t\t\t\t\t\t\talt=\"\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"cont_form_login\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" onclick=\"ocultar_login_sign_up()\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"material-icons\">&#xE5C4;</i></a>\n");
      out.write("\t\t\t\t\t\t<h2>LOGIN</h2>\n");
      out.write("\t\t\t\t\t\t<form action=\"\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Email or Login\" /> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" placeholder=\"Password\" /> <input type=\"submit\"\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"LOGIN\" class=\"btn_login\" />\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"cont_form_sign_up\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" onclick=\"ocultar_login_sign_up()\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"material-icons\">&#xE5C4;</i></a>\n");
      out.write("\t\t\t\t\t\t<h2>SIGN UP</h2>\n");
      out.write("\t\t\t\t\t\t<form action=\"./../servlet/inscrp_user\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" autocomplete=\"on\" placeholder=\"Email\" name=\"email\" required/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" autocomplete=\"on\" placeholder=\"Login\" name=\"login\"required/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" autocomplete=\"on\" placeholder=\"User Name\" name=\"name\" required/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" autocomplete=\"on\" placeholder=\"User FirstName\" name=\"firstname\" required/>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" autocomplete=\"on\" placeholder=\"Password\" name=\"password\"required/> \n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" autocomplete=\"on\" placeholder=\"Confirm Password\" name=\"password2\"required/>\n");
      out.write("\t\t\t\t\t\t\t<input class=\"btn_sign_up\" type=\"submit\" value=\"SIGN UP\" />\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script src=\"../js/accueil.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
